### ISSUE TITLE
Can not update entity

### ISSUE THREAD

**Issue by datastory** [pexip/os-python-azure-storage#1]
Update entity task 

`task = {'PartitionKey': 'tasksSeattle', 'RowKey': '1', 'description' : 'Take out the garbage', 'priority' : 250}`

`table_service.update_entity('tasktable', 'tasksSeattle', '1', task, content_type='application/atom+xml')`
 
written according to [docs](https://docs.microsoft.com/en-us/azure/storage/storage-python-how-to-use-table-storage) throws `TypeError: The entity must be either in dict format or an entity object.`

**Comment by bjhockley** [comment]
Hi @datastory  - this repo is for a custom fork of the azure-storage package  (which is not the version that people outside of our organisation will use)

You'll  need to report this issue to the mainline package owner here https://github.com/Azure/azure-storage-python
